name       : cvassistant
version    : 3.1.0
release    : 2
source     :
    - https://ufpr.dl.sourceforge.net/project/cvassistant/cvassistant-3.1.0-src.tar.bz2 : 27efa6220287fb33fdb355f03533d3724d265022adc1f640a93cfaaf164046f8
license    : GPL-3.0-or-later
component  : office
summary    : World most advanced job application software
description: |
    CV Assistant helps you create specialized resumes in Word .docx format fast and easy.
builddeps  :
    - pkgconfig(Qt5Core)
    - quazip-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Patch-for-quazip.patch
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
